services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    environment:
      NODE_ENV: development
    env_file:
      - ./apps/api-gateway/.env
    ports:
      - 3000:3000

  balance-service:
    container_name: balance-service
    build:
      context: .
      dockerfile: ./apps/balance/Dockerfile
    environment:
      NODE_ENV: development
    env_file:
      - ./apps/balance/.env
    ports:
      - 3001:3001
    depends_on:
      postgres-balance:
        condition: service_healthy

  rate-service:
    container_name: rate-service
    build:
      context: .
      dockerfile: ./apps/rate/Dockerfile
    environment:
      NODE_ENV: development
    env_file:
      - ./apps/rate/.env
    ports:
      - 3002:3002

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
    environment:
      NODE_ENV: development
    env_file:
      - ./apps/user/.env
    ports:
      - 3003:3003
    depends_on:
      postgres-user:
        condition: service_healthy

  postgres-balance:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - postgres-balance-password
    volumes:
      - postgres-balance-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=balances_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-balance-password
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-user:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - postgres-user-password
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-user-password
    ports:
      - 5433:5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-balance-data:
  postgres-user-data:
secrets:
  postgres-balance-password:
    file: ./apps/balance/db/password.txt
  postgres-user-password:
    file: ./apps/user/db/password.txt
